version: '3.8'
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data 
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
