version: '3.8'
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/event-manager.db
    restart: unless-stopped
